---
packages_pacman_packages:
  - curl
  - unzip
  - 7zip
  - gnu-free-fonts
  - ttf-inconsolata
  - steam
  - wine-staging
  - mission-center
  - newsflash
  - protonplus
  - obs-studio
  - vlc
  - libreoffice-fresh
  - lutris
  - heroic-games-launcher
  - go-task
  - rbenv
  - rustup
  - godot-mono
  - dotnet-sdk
  - dotnet-sdk-8.0
  - aspnet-runtime
  - qbittorrent
  - ttf-roboto-mono
  - gnome-tweaks
  - extension-manager
  - gnome-menus
  - gnome-boxes
  - gstreamer
  - gst-plugins-base
  - gst-plugins-good
  - gst-plugins-bad
  - gst-plugins-ugly
  - gst-libav
  - gst-plugin-va

packages_aur_packages:
  - visual-studio-code-bin
  - gapless
  - papirus-icon-theme-git
  - opera

packages_flatpak_packages_required:
  - flatpak

packages_flatpak_default_remote: flathub

packages_flatpak_remotes:
  - name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

packages_flatpak_packages:
  - com.usebottles.bottles
